spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/asmara
    username: asmara
    password: asmara
    driver-class-name: org.postgresql.Driver
