import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKotlinMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}

// Supabase URL/key come from local.properties, which is gitignored, so no
// real project value ever hits git.
val localProperties = Properties().apply {
    val file = rootProject.file("local.properties")
    if (file.exists()) file.inputStream().use(::load)
}

fun supabaseSetting(propertyKey: String, default: String): String =
    localProperties.getProperty(propertyKey) ?: default

val supabaseUrl = supabaseSetting("supabase.url", "https://your-project-ref.supabase.co")
val supabasePublishableKey = supabaseSetting("supabase.publishableKey", "sb_publishable_replace_me")

val generateSupabaseConfig = tasks.register("generateSupabaseConfig") {
    val outputDir = layout.buildDirectory.dir("generated/supabaseConfig/commonMain/kotlin")
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().asFile.resolve("com/conference/asmara/config/SupabaseConfig.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.conference.asmara.config

            // Generated by the :shared:generateSupabaseConfig Gradle task from local.properties.
            // See README.md#supabase. Do not edit directly; do not commit this file's real values.
            object SupabaseConfig {
                const val URL = "$supabaseUrl"
                const val PUBLISHABLE_KEY = "$supabasePublishableKey"
            }
            """.trimIndent()
        )
    }
}

kotlin {
    android {
        namespace = "com.conference.asmara"
        compileSdk = 36
        minSdk = 26
        androidResources.enable = true
        withHostTest {}
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateSupabaseConfig)
        }
        commonMain.dependencies {
            @Suppress("DEPRECATION")
            implementation(compose.runtime)
            @Suppress("DEPRECATION")
            implementation(compose.foundation)
            @Suppress("DEPRECATION")
            implementation(compose.material3)
            @Suppress("DEPRECATION")
            implementation(compose.ui)
            @Suppress("DEPRECATION")
            implementation(compose.components.resources)
            // api: androidApp/MainActivity references org.koin.core.module.Module directly
            // (App()'s platformModule parameter type), so it needs this on its compile classpath.
            api(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.voyager.navigator)
            implementation(libs.voyager.screenmodel)
            implementation(project.dependencies.platform(libs.supabase.bom))
            implementation(libs.supabase.postgrest)
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqldelight.android.driver)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
            implementation(libs.sqldelight.native.driver)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.koin.test)
        }
        // Test-only in-memory driver, one per target so the same commonTest
        // suite (mapper, local data source, repository, integration) runs on
        // both `testAndroidHostTest` (fast, plain JVM) and iosSimulatorArm64Test.
        getByName("androidHostTest").dependencies {
            implementation(libs.sqldelight.sqlite.driver)
        }
        iosTest.dependencies {
            implementation(libs.sqldelight.native.driver)
        }
    }
}

// The generated `Res` class package is pinned explicitly. Its derived default is
// long and has changed shape between Compose Multiplatform releases, so pinning
// keeps the `Res` imports in ui/theme/Type.kt from churning on every upgrade.
compose.resources {
    publicResClass = false
    packageOfResClass = "com.conference.asmara.resources"
    generateResClass = auto
}

sqldelight {
    databases {
        create("ScheduleDatabase") {
            packageName.set("com.conference.asmara.db")
        }
    }
}
